//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mimics.rc
//
#define IDB_MIMICSLINECTRL              101
#define IDB_MIMICSRECTANGLECTRL         102
#define IDB_MIMICSELLIPSECTRL           103
#define IDB_MIMICSARCCTRL               104
#define IDB_MIMICSTRIANGLECTRL          105
#define IDB_MIMICSSWITCHCTRL            106
#define IDB_MIMICSTEXTCTRL              107
#define IDB_MIMICSIMAGECTRL             108
#define IDB_MIMICSGROUPCTRL             109
#define IDB_MIMICSOBJECTCTLHATCHSOLID   110
#define IDB_MIMICSOBJECTCTLHATCHHORIZONTAL 111
#define IDB_MIMICSOBJECTCTLHATCHVERTICAL 112
#define IDB_MIMICSOBJECTCTLHATCHDIAGONALDOWN 113
#define IDB_MIMICSOBJECTCTLHATCHDIAGONALUP 114
#define IDB_MIMICSOBJECTCTLHATCHCROSS   115
#define IDB_MIMICSOBJECTCTLHATCHCROSSDIAGONAL 116
#define IDB_MIMICSOBJECTCTLHATCHPOINTSLOW 117
#define IDB_MIMICSOBJECTCTLHATCHPOINTSMEDIUM 118
#define IDB_MIMICSOBJECTCTLHATCHPOINTSHIGH 119
#define IDB_ALIGNMENTCOMBOBOXSYMBOLLEFTTOP 120
#define IDB_ALIGNMENTCOMBOBOXSYMBOLLEFTMIDDLE 121
#define IDB_ALIGNMENTCOMBOBOXSYMBOLLEFTBOTTOM 122
#define IDB_ALIGNMENTCOMBOBOXSYMBOLCENTERTOP 123
#define IDB_ALIGNMENTCOMBOBOXSYMBOLCENTERMIDDLE 124
#define IDB_ALIGNMENTCOMBOBOXSYMBOLCENTERBOTTOM 125
#define IDB_ALIGNMENTCOMBOBOXSYMBOLRIGHTTOP 126
#define IDB_ALIGNMENTCOMBOBOXSYMBOLRIGHTMIDDLE 127
#define IDB_ALIGNMENTCOMBOBOXSYMBOLRIGHTBOTTOM 128
#define IDB_HATCHESCOMBOBOXPATTERNSOLID 129
#define IDB_HATCHESCOMBOBOXPATTERNHORIZONTAL 130
#define IDB_HATCHESCOMBOBOXPATTERNVERTICAL 131
#define IDB_HATCHESCOMBOBOXPATTERNDIAGONALDOWN 132
#define IDB_HATCHESCOMBOBOXPATTERNDIAGONALUP 133
#define IDB_HATCHESCOMBOBOXPATTERNCROSS 134
#define IDB_HATCHESCOMBOBOXPATTERNCROSSDIAGONAL 135
#define IDB_HATCHESCOMBOBOXPATTERNPOINTSLOW 136
#define IDB_HATCHESCOMBOBOXPATTERNPOINTSMEDIUM 137
#define IDB_HATCHESCOMBOBOXPATTERNPOINTSHIGH 138
#define IDB_FONTSCOMBOBOXFONTPRINTER    139
#define IDB_FONTSCOMBOBOXFONTTRUETYPE   140
#define IDD_MIMICSLINE_GENERALPAGE      141
#define IDD_MIMICSLINE_OUTLINEPAGE      142
#define IDD_MIMICSRECTANGLE_GENERALPAGE 143
#define IDD_MIMICSRECTANGLE_OUTLINEPAGE 144
#define IDD_MIMICSELLIPSE_GENERALPAGE   145
#define IDD_MIMICSELLIPSE_OUTLINEPAGE   146
#define IDD_MIMICSARC_GENERALPAGE       147
#define IDD_MIMICSARC_OUTLINEPAGE       148
#define IDD_MIMICSTRIANGLE_GENERALPAGE  149
#define IDD_MIMICSTRIANGLE_OUTLINEPAGE  150
#define IDD_MIMICSSWITCH_GENERALPAGE    151
#define IDD_MIMICSSWITCH_OUTLINEPAGE    152
#define IDD_MIMICSTEXT_GENERALPAGE      153
#define IDD_MIMICSTEXT_FONTPAGE         154
#define IDD_MIMICSTEXT_OUTLINEPAGE      155
#define IDD_MIMICSIMAGE_GENERALPAGE     156
#define IDD_MIMICSIMAGE_OUTLINEPAGE     157
#define IDD_MIMICSGROUP_GENERALPAGE     158

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
