//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SCOS-2000.rc
//
#define IDR_DATABASE_DERIVATIONCODE_PROCEDURES 101
#define IDR_DATABASE_DERIVATIONCODE_INITIALIZATION 102
#define IDD_DATABASE_OBPROCESSORS_IMPORT_DIALOG 103
#define IDD_DATABASE_OBPROCESSORS_EXPORT_DIALOG 104
#define IDD_DATABASE_MEMORYIMAGES_IMPORT_DIALOG 105
#define IDD_DATABASE_MEMORYIMAGES_EXPORT_DIALOG 106
#define IDD_DATABASE_TABLES_IMPORT_DIALOG 107
#define IDD_DATABASE_TABLES_EXPORT_DIALOG 108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
